version: "3.9"

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    environment:
      DOCKER_RUN: "True"
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT_FORWARD}:${BACKEND_PORT}
    command: python run.py

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
    env_file:
      - .env
    environment:
      REACT_APP_BACKEND_IP: ${FRONTEND_IP}
      REACT_APP_BACKEND_PORT: ${BACKEND_PORT_FORWARD}
    ports:
      - ${FRONTEND_PORT_FORWARD}:${FRONTEND_PORT}
    volumes:
      - ./build:/source/build/
    depends_on:
      - backend
    command: npm start -p ${FRONTEND_PORT_FORWARD}
