version: "3.9"

services:


  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    command: python run.py

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
    ports:
      - 80:3000
    depends_on:
      - backend
    command: serve -p 3000